---
- hosts: rhel
  tasks:
  - name: command module
    command: hostname -f
    register: cmd_content
  - name: print content
    debug: msg="{{ cmd_content }}"
  - name: print error
    debug: msg="{{ cmd_content.stderr }}"
    when: cmd_content != ""
  - debug: " OS family is {{ansible_os_family }}"
    